server:
    port: 9094

spring:
    application:
        name: Config-Server
    cloud:
        config:
            server:
                git:
                    url:
                        clone-on-start: true
